# Generated by Django 5.0.2 on 2024-02-21 11:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('faculty_fields', '0001_initial'),
        ('universities', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Faculty name')),
                ('acceptance', models.PositiveSmallIntegerField(verbose_name='Acceptance number')),
                ('grant', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='Grand score')),
                ('contract', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='Contract score')),
                ('education_form', models.ManyToManyField(to='faculty_fields.education_forms', verbose_name='Education form')),
                ('first_subject', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='faculty_fields.subject', verbose_name='First subject')),
                ('second_subject', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='faculty_fields.subject', verbose_name='Second subject')),
                ('tuition_language', models.ManyToManyField(to='faculty_fields.tuition_language', verbose_name='Tuition language')),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='universities.university', verbose_name='University')),
            ],
            options={
                'verbose_name': 'Faculty',
                'verbose_name_plural': 'Faculties',
            },
        ),
    ]
