# Generated by Django 5.0.2 on 2024-02-21 11:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0001_initial'),
        ('faculty_fields', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty',
            name='first_subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='faculty_fields.subject', verbose_name='First subject'),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='second_subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='faculty_fields.subject', verbose_name='Second subject'),
        ),
    ]
