# Generated by Django 5.0.2 on 2024-02-19 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Name of the university')),
                ('address', models.TextField(verbose_name='Address of the university')),
                ('phone_number', models.CharField(max_length=13, verbose_name='University phone number')),
                ('image', models.ImageField(upload_to='university-images/', verbose_name='Image of the university')),
            ],
            options={
                'verbose_name': 'University',
                'verbose_name_plural': 'Universities',
            },
        ),
    ]
